[theme]
primaryColor = "#4e8cff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
base = "light"

[server]
headless = true
maxUploadSize = 200
address = "localhost"
enableCORS = false
enableXsrfProtection = false